# Generated by Django 4.2 on 2026-05-21 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_block', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
